name: app_logger
description: A reusable logging package for Flutter applications using Talker
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.9.0
  flutter: ^3.35.1

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  talker_flutter: ^4.9.3
  riverpod: ^2.6.1
  firebase_crashlytics: ^4.3.10
  riverpod_annotation: ^2.6.1

dev_dependencies:
  build_runner: ^2.5.4
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.6.5
  flutter_lints: ^6.0.0
  yumemi_lints: ^4.2.0

flutter:
