name: debug
description: Debug package with Talker integration and shake detector
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.6.0
  flutter: '>=3.10.0'

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  go_router: ^15.2.3
  hooks_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  shake_detector: ^0.1.2
  talker_flutter: ^4.4.0
  talker_riverpod_logger: ^4.4.0

dev_dependencies:
  build_runner: ^2.5.3
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.6.5
  yumemi_lints: ^4.1.1

flutter:
