name: debug
description: Debug package with Talker integration and shake detector
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  hooks_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  talker_flutter: ^4.4.0
  talker_riverpod_logger: ^4.4.0
  shake_detector: ^0.1.2
  go_router: ^15.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.6.5
  build_runner: ^2.5.3
  flutter_lints: ^6.0.0

flutter:
