name: 'Check File Changes'
description: 'Check for specific file type changes in PR'
author: 'r0227n'

inputs:
  base_sha:
    description: 'Base commit SHA for comparison'
    required: true
  head_sha:
    description: 'Head commit SHA for comparison'
    required: true

outputs:
  dart_changed:
    description: 'Number of .dart files changed'
    value: ${{ steps.check_changes.outputs.dart_changed }}
  yml_changed:
    description: 'Number of .yml files changed'
    value: ${{ steps.check_changes.outputs.yml_changed }}
  yaml_changed:
    description: 'Number of .yaml files changed'
    value: ${{ steps.check_changes.outputs.yaml_changed }}
  md_changed:
    description: 'Number of .md files changed'
    value: ${{ steps.check_changes.outputs.md_changed }}
  i18n_changed:
    description: 'Number of .i18n.json files changed'
    value: ${{ steps.check_changes.outputs.i18n_changed }}
  changed_workspaces:
    description: 'List of changed workspaces (space-separated)'
    value: ${{ steps.check_changes.outputs.changed_workspaces }}
  app_changed:
    description: 'Whether app workspace changed'
    value: ${{ steps.check_changes.outputs.app_changed }}
  app_logger_changed:
    description: 'Whether app_logger workspace changed'
    value: ${{ steps.check_changes.outputs.app_logger_changed }}
  app_preferences_changed:
    description: 'Whether app_preferences workspace changed'
    value: ${{ steps.check_changes.outputs.app_preferences_changed }}

runs:
  using: 'composite'
  steps:
    - name: Check for file changes
      id: check_changes
      shell: bash
      run: |
        # Get changed files in PR
        CHANGED_FILES=$(git diff --name-only ${{ inputs.base_sha }}..${{ inputs.head_sha }})

        # Check for specific file types
        echo "dart_changed=$(echo "$CHANGED_FILES" | grep -E '\.dart$' | wc -l | xargs)" >> $GITHUB_OUTPUT
        echo "yml_changed=$(echo "$CHANGED_FILES" | grep -E '\.yml$' | wc -l | xargs)" >> $GITHUB_OUTPUT
        echo "yaml_changed=$(echo "$CHANGED_FILES" | grep -E '\.yaml$' | wc -l | xargs)" >> $GITHUB_OUTPUT
        echo "md_changed=$(echo "$CHANGED_FILES" | grep -E '\.md$' | wc -l | xargs)" >> $GITHUB_OUTPUT
        echo "i18n_changed=$(echo "$CHANGED_FILES" | grep -E '\.i18n\.json$' | wc -l | xargs)" >> $GITHUB_OUTPUT

        # Dynamically detect changed workspaces
        CHANGED_WORKSPACES=""

        # Check for app directory
        if echo "$CHANGED_FILES" | grep -q "^app/"; then
          CHANGED_WORKSPACES="$CHANGED_WORKSPACES app"
        fi

        # Check for packages subdirectories
        for package_dir in packages/*/; do
          if [ -d "$package_dir" ]; then
            package_name=$(basename "$package_dir")
            if echo "$CHANGED_FILES" | grep -q "^packages/$package_name/"; then
              CHANGED_WORKSPACES="$CHANGED_WORKSPACES $package_name"
            fi
          fi
        done

        # Trim leading whitespace
        CHANGED_WORKSPACES=$(echo "$CHANGED_WORKSPACES" | xargs)

        echo "changed_workspaces=$CHANGED_WORKSPACES" >> $GITHUB_OUTPUT

        # Legacy outputs for backward compatibility
        if echo "$CHANGED_WORKSPACES" | grep -q "\bapp\b"; then
          echo "app_changed=true" >> $GITHUB_OUTPUT
        else
          echo "app_changed=false" >> $GITHUB_OUTPUT
        fi

        if echo "$CHANGED_WORKSPACES" | grep -q "\bapp_logger\b"; then
          echo "app_logger_changed=true" >> $GITHUB_OUTPUT
        else
          echo "app_logger_changed=false" >> $GITHUB_OUTPUT
        fi

        if echo "$CHANGED_WORKSPACES" | grep -q "\bapp_preferences\b"; then
          echo "app_preferences_changed=true" >> $GITHUB_OUTPUT
        else
          echo "app_preferences_changed=false" >> $GITHUB_OUTPUT
        fi

        # Debug output
        echo "Changed files:"
        echo "$CHANGED_FILES"
        echo "Dart files changed: $(echo "$CHANGED_FILES" | grep -E '\.dart$' | wc -l | xargs)"
        echo "YML files changed: $(echo "$CHANGED_FILES" | grep -E '\.yml$' | wc -l | xargs)"
        echo "YAML files changed: $(echo "$CHANGED_FILES" | grep -E '\.yaml$' | wc -l | xargs)"
        echo "MD files changed: $(echo "$CHANGED_FILES" | grep -E '\.md$' | wc -l | xargs)"
        echo "i18n files changed: $(echo "$CHANGED_FILES" | grep -E '\.i18n\.json$' | wc -l | xargs)"
        echo "Changed workspaces: $CHANGED_WORKSPACES"
