include: package:yumemi_lints/flutter/3.32/recommended.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore
  plugins:
    # TODO: Re-enable custom_lint after Flutter 3.35.1 compatibility
    # - custom_lint

formatter:
  trailing_commas: preserve
