include: package:yumemi_lints/flutter/3.35/recommended.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore
  plugins:
    # TODO: custom_lint v0.8.0 以上にあげれたら、コメントアウトを解除する
    # - custom_lint

formatter:
  trailing_commas: preserve
