targets:
  $default:
    builders:
      slang_build_runner:
        options:
          base_locale: ja
          fallback_strategy: base_locale
          input_directory: assets/i18n
          input_file_pattern: .i18n.json
          output_directory: lib/i18n
          output_file_name: core_translations.g.dart
          output_format: single_file
          locale_handling: true
          flutter_integration: true
          namespaces: false
          translate_var_names: true
          flat_map: false
          stats: true
          format:
            enabled: true
          timestamp: false
          enum_name: CoreLocale
          class_name: CoreTranslations
