name: 'Setup Flutter'
description: 'Sets up Flutter Version Management (FVM) with the correct Flutter version'

inputs:
  flutter-version-override:
    description: 'Optional Flutter version to override the one in .fvmrc'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    # Update .fvmrc if override is provided
    - name: Override Flutter Version in .fvmrc
      if: inputs.flutter-version-override != ''
      shell: bash
      run: |
        echo '{"flutter": "${{ inputs.flutter-version-override }}"}' > .fvmrc

    # https://github.com/kuhnroyal/flutter-fvm-config-action
    - name: Fetch flutter config
      uses: kuhnroyal/flutter-fvm-config-action@34c3905bc939a4ff9d9cb07d5a977493fa73b2aa # v2.0
      id: fvm-config-action

    # https://github.com/subosito/flutter-action
    - name: Setup flutter
      uses: subosito/flutter-action@1c5eb12d812966ca84680edc38353a0851c8fd56 # v2.14.0
      with:
        flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
        channel: ${{ steps.fvm-config-action.outputs.FLUTTER_CHANNEL }}
        cache: true

    # Parse melos version from pubspec.yaml
    - name: Get melos version
      id: melos-version
      shell: bash
      run: |
        MELOS_VERSION=$(grep "melos:" pubspec.yaml | head -1 | awk '{print $2}' | sed 's/\^//')
        echo "version=$MELOS_VERSION" >> $GITHUB_OUTPUT

    # Setup melos
    - name: Setup melos
      uses: bluefireteam/melos-action@c7dcb921b23cc520cace360b95d02b37bf09cdaa # v3.0.0
      with:
        melos-version: ${{ steps.melos-version.outputs.version }}
