name: apps
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1
  flutter: ^3.32.2

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_hooks: ^0.21.2
  freezed_annotation: ^3.0.0
  go_router: ^15.1.2
  hooks_riverpod: ^2.6.1
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.6.1
  slang: ^4.7.2
  slang_flutter: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.15
  freezed: ^3.0.6
  go_router_builder: ^2.9.0
  json_serializable: ^6.9.5
  riverpod_generator: ^2.6.5
  slang_build_runner: ^4.7.0

  custom_lint: ^0.7.5
  flutter_lints: ^5.0.0
  freezed_lint: ^0.0.9
  riverpod_lint: ^2.6.5
  yumemi_lints: ^4.1.1


flutter:

  uses-material-design: true