name: Renovate

on:
  schedule:
    # Run every Friday at 8:00 PM JST (11:00 AM UTC)
    - cron: '0 11 * * 5'
  push:
    branches:
      - fix/renovete
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Override default log level'
        type: choice
        default: 'info'
        options:
          - 'info'
          - 'debug'
          - 'trace'
      overrideSchedule:
        description: 'Override all schedules'
        type: boolean
        default: false

env:
  # https://docs.renovatebot.com/troubleshooting/#log-debug
  LOG_LEVEL: ${{ inputs.logLevel || 'info' }}
  # https://docs.renovatebot.com/self-hosted-configuration/#repositories
  RENOVATE_REPOSITORIES: ${{ github.repository }}
  # https://docs.renovatebot.com/configuration-options/#repotoken
  RENOVATE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # https://docs.renovatebot.com/configuration-options/#gitauthor
  RENOVATE_GIT_AUTHOR: 'Renovate Bot <bot@renovateapp.com>'
  # https://docs.renovatebot.com/configuration-options/#platformcommit
  RENOVATE_PLATFORM_COMMIT: 'true'

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.1.12
        with:
          configurationFile: .github/renovate.json5
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          RENOVATE_CONFIG_FILE: .github/renovate.json5
          RENOVATE_AUTODISCOVER: false
          RENOVATE_SCHEDULE_AUTOMERGE: ${{ inputs.overrideSchedule == true && 'at any time' || '' }}
